### ISSUE TITLE
Missing capability to add VNET Peering to Azure VRF

### ISSUE THREAD

**Issue by ddastoli** [CiscoDevNet/ansible-mso#127]
When creating a new VRF for Azure site, we are missing the capability to define this VRD with VNET Peering. SOmething like mso_schema_site_vrf_region_hub_network for AWS, should be provided for Azure, i.e. mso_schema_site_vrf_region_vnet_peering. Also with this module, two features at least would be required:
1- the possibility to disable the VPN Gateway Router which is automatically attached to the VRF at creation(cisco.mso.mso_schema_site_vrf_region_cidr).
2- there should be also a way to add the name of the vnet peering.

**Comment by lhercot** [comment]
@ddastoli This is already supported today as part of mso_schema_site_vrf_region_hub_network and mso_schema_site_vrf_region

Here is an example on how to achieve this:
```
- name: MSO TESTING
  hosts: localhost
  tasks:
  - name: Set vars
    set_fact: 
      mso_info: &mso_info
        host: {{ mso_ip }}
        username: {{ mso_user }}
        password: {{ mso_password }}
        validate_certs: '{{ mso_validate_certs | default(false) }}'
        use_ssl: '{{ mso_use_ssl | default(true) }}'
        use_proxy: '{{ mso_use_proxy | default(true) }}'
        output_level: '{{ mso_output_level | default("info") }}'

  - name: Ensure tenant ansible_test exist
    cisco.mso.mso_tenant: 
      <<: *mso_info
      tenant: ansible_test
      state: present

  - name: Ensure Azure site is present under tenant ansible_test
    cisco.mso.mso_tenant_site: 
      <<: *mso_info
      tenant: ansible_test
      site: Azure-West
      cloud_account: uni/tn-ansible_test/act-[9]-vendor-azure
      state: present

  - name: Ensure schema 1 with Template 1
    cisco.mso.mso_schema_template: 
      <<: *mso_info
      schema: '{{ mso_schema | default("ansible_test") }}'
      tenant: ansible_test
      template: '{{ item }}'
      state: present
    loop:
    - Template 1

  - name: Ensure VRF1 exists
    cisco.mso.mso_schema_template_vrf: 
      <<: *mso_info
      schema: '{{ mso_schema | default("ansible_test") }}'
      template: Template 1
      vrf: VRF1
      state: present

  - name: Add a new CIDR in VRF1 at Azure site level
    cisco.mso.mso_schema_site_vrf_region_cidr:
      <<: *mso_info
      schema: '{{ mso_schema | default("ansible_test") }}'
      template: Template 1
      site: Azure-West
      vrf: VRF1
      region: westus
      cidr: 10.1.0.0/16
      primary: true
      state: present

  - name: Add hub network in VRF1 region westus at Azure site level
    cisco.mso.mso_schema_site_vrf_region_hub_network:
      <<: *mso_info
      schema: '{{ mso_schema | default("ansible_test") }}'
      template: Template 1
      site: Azure-West
      vrf: VRF1
      region: westus
      hub_network:
        name: default
        tenant: infra
      state: present

  - name: Remove VPN Gateway Router at Region for Azure
    cisco.mso.mso_schema_site_vrf_region:
      <<: *mso_info
      schema: '{{ mso_schema | default("ansible_test") }}'
      template: Template 1
      site: Azure-West
      vrf: VRF1
      region: westus
      vpn_gateway_router: false
      state: present
```
