### ISSUE TITLE
mso_schema_site_anp_epg_staticport: value of type must be one of: port, got: vpc

### ISSUE THREAD

**Issue by RonaldBlom** [CiscoDevNet/ansible-mso#228]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* module is not working when type/path_type is vpc
* error is: value of type must be one of: port, got: vpc
* and login_domain is not a valid option when type is vpc

### Affected Module Name(s):

* mso_schema_site_anp_epg_staticport

### MSO version and MSO Platform

* V 3.5.2f and ND-based

### APIC version and APIC Platform for Site Level Resources

* V 4.2.6h and on-prem

### Collection versions

* cisco.mso 1.3.0

### Output/ Error message

*  value of type must be one of: port, got: vpc

### Expected Behavior

*  input vpc should have been accepted and binding should be created

### Actual Behavior

*  see error

### Playbook tasks to Reproduce

failed: [host] (item=[{'vrf_name': 'test_vpn_1', 'ap_name': 'ap_test_vpn_1', 'epg_name': 'epg_vlan_0701', 'epg_int_mode': 'regular'}, {'pod_id': '1', 'leaf_id': '103-104', 'port': '1/1'}]) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "anp": "ap_test_vpn_1",
            "deployment_immediacy": "lazy",
            "epg": "epg_vlan_0701",
            "host": "host",
            "leaf": "103-104",
            "mode": "regular",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "server1",
            "pod": "pod-1",
            "schema": "test_vpn_1",
            "site": "site1",
            "state": "present",
            "template": "test_vpn_1_site1-site2",
            "timeout": 30,
            "type": "vpc",
            "use_proxy": true,
            "use_ssl": true,
            "username": "user",
            "validate_certs": false,
            "vlan": 701
        }
    },
    "item": [
        {
            "ap_name": "ap_test_vpn_1",
            "epg_int_mode": "regular",
            "epg_name": "epg_vlan_0701",
            "vrf_name": "test_vpn_1"
        },
        {
            "leaf_id": "103-104",
            "pod_id": "1",
            "port": "1/1"
        }
    ],
    "msg": "value of type must be one of: port, got: vpc"
}

*

### Important Factoids

 no, nothing

### References

* #0000

**Comment by notsharkbait** [comment]
Hi Ronald - It would be helpful if you could attach your playbook to make it easier to troubleshoot.

**Comment by mminnen** [comment]
👍

**Comment by RonaldBlom** [comment]
- name: Create static binding to EPG for VPC
  mso_schema_site_anp_epg_staticport:
    host: "{{ ansible_host }}"
    username: "{{ mso_username }}"
    password: "{{ mso_password }}"
    # login_domain: "{{ mso_login_domain }}"
    validate_certs: "{{ validate_certs }}"
    schema: "{{ tenant }}_{{ item.0.vrf_name }}"
    template: "{{ item.0.vrf_name }}_{{ lookup('vars', site)|lower }}"
    site: "{{ aci_change_deploy_site }}" 
    anp: "{{ item.0.ap_name }}"
    epg: "{{ item.0.epg_name }}"
    pod: "pod-{{ item.1.pod_id }}"
    leaf: "{{ item.1.leaf_id }}"
    path: "{{ aci_change_interface_policy_group_name|lower }}"
    vlan: "{{ item.0.epg_name[-4:] }}"
    type: "{{ aci_change_interface_type }}"
    mode: "{{ item.0.epg_int_mode }}"
    deployment_immediacy: "{{ deploy_immediacy }}"
    state: present
  loop: '{{ aci_change_epg_list | product(aci_change_epg_binding_parsed)|list }}'
  when: aci_change_interface_type == 'vpc'

**Comment by RonaldBlom** [comment]
the above loop, when and variables are ending up in this invocation:
"invocation": {
        "module_args": {
            "anp": "ap_test_vpn_1",
            "deployment_immediacy": "lazy",
            "epg": "epg_vlan_0701",
            "host": "te--se99002.mgmt-o.rabobank.nl",
            "leaf": "103-104",
            "mode": "regular",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "xsrv9932.1",
            "pod": "pod-1",
            "schema": "rabobank_test_vpn_1",
            "site": "af91",
            "state": "present",
            "template": "test_vpn_1_af91-af92",
            "timeout": 30,
            "type": "vpc",
            "use_proxy": true,
            "use_ssl": true,
            "username": "eu.Ciscoacitest",
            "validate_certs": false,
            "vlan": 701

**Comment by RonaldBlom** [comment]
If more info is needed, please let me know

**Comment by shrsr** [comment]
@RonaldBlom Can you please share the playbook you are using too?

**Comment by RonaldBlom** [comment]
Do you mean the whole playbook? or only the task which calls the module? The last one is already shared above.

**Comment by shrsr** [comment]
I was unable to reproduce the issue with your task alone. It would help us a lot if you could provide us with the entire playbook if possible.

**Comment by shrsr** [comment]
@RonaldBlom I ran a playbook configured with the task provided above on MSO and NDO, but I couldn't use the condition and loop statements used in the task due to lack of knowledge of the configuration used in other tasks of your playbook. Hence, I was unable to reproduce the issue. To further debug the issue it would help us if you provided the entire playbook. Please let us know if you have any questions.

**Comment by RonaldBlom** [comment]
Hi, here the play we are using. If you switch in the vars section to port it succeeds, but when switching to vpc, we get the error.

---

- name: Bind vlan to EPG
  hosts: mso
  connection: local
  gather_facts: no
  
  vars:
    aci_change_interface_type: port
    interface_policy_group_name: "server.1"
    port: "eth1/23"
    task: bind_vlan_to_epg_full_mso
  tasks:
    - name: Create static binding to EPG for VPC
      mso_schema_site_anp_epg_staticport:
        host: "{{ ansible_host }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        # login_domain: "{{ mso_login_domain }}"
        validate_certs: "no"
        schema: "test_vpn_1"
        template: "test_vpn_1_both-sites"
        site: "site1" 
        anp: "ap_test_vpn_1"
        epg: "epg_vlan_0701"
        pod: "pod-1"
        leaf: "101_102"
        path: "{{ interface_policy_group_name|lower }}"
        vlan: "0701"
        type: "vpc"
        mode: "regular"
        deployment_immediacy: "immediate"
        state: present
      when: aci_change_interface_type == 'vpc'

    - name: Create static binding to EPG for Access Port
      cisco.mso.mso_schema_site_anp_epg_staticport:
        host: "{{ ansible_host }}"
        username: "{{ mso_username }}"
        password: "{{ mso_password }}"
        login_domain: "{{ mso_login_domain }}"
        validate_certs: "no"
        schema: "test_vpn_1"
        template: "test_vpn_1_both-sites"
        site: "site1" 
        anp: "ap_test_vpn_1"
        epg: "epg_vlan_0701"
        pod: "pod-1"
        leaf: "101"
        path: "{{ port }}"
        vlan: "0701"
        type: "port"
        mode: "regular"
        deployment_immediacy: "immediate"
        state: present
      when: aci_change_interface_type == 'port'

**Comment by shrsr** [comment]
@RonaldBlom I borrowed your tasks and added them to my playbook but was unable to reproduce the issue after running it. I have shared the playbook below for reference. Can you please run the following and see if you face the same error?

```
---
- name: Test1
  hosts: localhost
  collections:
    - cisco.mso

  vars:
    aci_change_interface_type: vpc
    interface_policy_group_name: "server.1"
    port: "eth1/23"
    task: bind_vlan_to_epg_full_mso
   
  tasks:

  - name: Add a new template to a schema
    cisco.mso.mso_schema_template:
      host: HOST
      username: USER
      password: PWD
      validate_certs: False
      tenant: Tenant1
      schema: dc_schema
      template: dc1_template
      state: present
    delegate_to: localhost

  - name: Add a new site to a schema
    cisco.mso.mso_schema_site:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      site: TF_test
      template: dc1_template
      state: present
    delegate_to: localhost

  - name: Add a new ANP
    cisco.mso.mso_schema_template_anp:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      template: dc1_template
      anp: dc1-test_ap
      state: present
    delegate_to: localhost

  - name: Add a new VRF
    cisco.mso.mso_schema_template_vrf:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      template: dc1_template
      vrf: vrf
      state: present
    delegate_to: localhost

  - name: Add a new BD
    cisco.mso.mso_schema_template_bd:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      template: dc1_template
      bd: bd
      vrf:
        name: vrf
      state: present
    delegate_to: localhost

  - name: Add a new EPG
    cisco.mso.mso_schema_template_anp_epg:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      template: dc1_template
      anp: dc1-test_ap
      epg: epg
      bd:
        name: bd
      vrf:
        name: vrf
      state: present
    delegate_to: localhost

  - name: Create a site ANP
    cisco.mso.mso_schema_site_anp:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      output_level: debug
      schema: dc_schema
      site: TF_test
      template: dc1_template
      anp: dc1-test_ap
      state: present
      use_proxy: false
    delegate_to: localhost
    register: query_result

  - name: Add a new site EPG
    cisco.mso.mso_schema_site_anp_epg:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      schema: dc_schema
      template: dc1_template
      anp: dc1-test_ap
      site: TF_test
      epg: epg
      state: present
    delegate_to: localhost

  - name: Create static binding to EPG for VPC
    cisco.mso.mso_schema_site_anp_epg_staticport:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      output_level: debug
      schema: dc_schema
      template: dc1_template
      site: TF_test
      anp: dc1-test_ap
      epg: epg
      pod: pod-1
      leaf: 101-103
      path: ansible_polgrp
      vlan: 126
      type: "{{port}}"
      mode: regular
      deployment_immediacy: immediate   
      state: present
    when: aci_change_interface_type == 'port'

  - name: Create static binding to EPG for VPC
    cisco.mso.mso_schema_site_anp_epg_staticport:
      host: HOST
      username: USR
      password: PWD
      validate_certs: False
      output_level: debug
      schema: dc_schema
      template: dc1_template
      site: TF_test
      anp: dc1-test_ap
      epg: epg
      pod: pod-1
      leaf: 101-103
      path: "{{ interface_policy_group_name|lower }}"
      vlan: 126
      type: vpc
      mode: regular
      deployment_immediacy: immediate
      state: present
    when: aci_change_interface_type == 'vpc'
```
