### ISSUE TITLE
NDO task timeout when use_ssl is default

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/ansible-mso#234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

NDO tasks in a playbook fail when use_ssl is not specified (timeout). However, when this is explicitly set to True (either on the module itself or by setting var ansible_httpapi_use_ssl) task works well.

### Affected Module Name(s):

Seems like any module is affected. Tested with modules:

* mso_tenant
* mso_schema_template

### MSO version and MSO Platform

* V 3.6.1e running on vND 2.1.2d 

### Collection versions

* cisco.mso 1.3.0

### Output/ Error message

```
fatal: [vnd01-mdr1.cisco.com]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "current": {}, "msg": "Authentication failed: Request failed: command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.", "previous": {}, "proposed": {}, "sent": {}}
```

### Expected Behavior

When `use_ssl` option is not specified, it should take default value, which is `True`

### Actual Behavior

When `use_ssl` option is not specified, module is failing due to a timeout.

Logs here: https://gist.github.com/adealdag/6a3b0dd96c97bafe6f8095cc86271e81

### Playbook tasks to Reproduce

```
- name: Tenant, schema and templates
  hosts: ndo
  connection: httpapi
  gather_facts: no

  vars:
    ndo_login: &ndo_login
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      login_domain: "{{ login_domain }}"
      validate_certs: no
    state: present

  tasks:
    - name: Create Tenant
      cisco.mso.mso_tenant:
        <<: *ndo_login
        tenant: ndo_ansible_demo
        display_name: ndo_ansible_demo
        users: 
          - "{{ ansible_user }}"
        sites:
          - "MDR1"
          - "MLG1"
        state: "{{ state }}"
```

Using inventory:

```
dc_spain:
  children:
    ndo:
      hosts:
        vnd01-mdr1.cisco.com:
          ansible_host: vnd01-mdr1.cisco.com
          ansible_user: orchestrator
          ansible_password: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            33623165663663616535363162653961353736383436306139636666653233346364353135303831
            3863633062366238613239336433303338343534393932370a616164303966363466616231653031
            62326464663763366335326631326535326431623633623536376332313835356137656639383461
            3633303832653962350a353536326333643032666434393034383132356237333862346263353334
            3839
          ansible_network_os: cisco.nd.nd
          login_domain: dcmdr1
```

### References

* #0000
