### ISSUE TITLE
mso_schema_template crash: A worker was found in a dead state

### ISSUE THREAD

**Issue by adealdag** [CiscoDevNet/ansible-mso#235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Module mso_schema_template crashes returning error `ERROR! A worker was found in a dead state`

The object gets created in NDO, but the playbook fails.

### Affected Module Name(s):

* mso_schema_template

### MSO version and MSO Platform

* V 3.6.1e on vND 2.1.2d

### Collection versions

* cisco.mso 1.3.0

### Output/ Error message

```
TASK [Add Schema and Template] ********************************************************************************************************************
objc[95528]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[95528]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
ERROR! A worker was found in a dead state
```

### Expected Behavior

Task should create Schema and Template in NDO and return ok/changed

### Actual Behavior

Task creates Schema and Template in NDO but then crashes and returns this error, and playbook fails

### Playbook tasks to Reproduce

````yaml
---
- name: Tenant, schema and templates
  hosts: ndo
  connection: httpapi
  gather_facts: no

  vars:
    ndo_login: &ndo_login
      login_domain: "{{ login_domain }}"
    state: present

  tasks:
    - name: Create Tenant
      cisco.mso.mso_tenant:
        <<: *ndo_login
        tenant: ndo_ansible_demo
        display_name: ndo_ansible_demo
        users: 
          - "{{ ansible_user }}"
        sites:
          - "MDR1"
          - "MLG1"
        state: "{{ state }}"

    - name: Add Schema and Template
      cisco.mso.mso_schema_template:
        <<: *ndo_login
        tenant: ndo_ansible_demo
        schema: ndo_ansible_demo
        template: Stretched
        state: "{{ state }}" 
````

### References

* #0000
