### ISSUE TITLE
Add description for EPG

### ISSUE THREAD

**Issue by sauguieb** [CiscoDevNet/ansible-mso#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In release 3.7, EPG description is exposed to NDO.
If ansible is not capable to push description, customer are forced to push EPG on NDO and then add the description on APIC site by site.

### New or Affected Module(s):
* mso_schema_template_anp_epg

### MSO version and MSO Platform
* NDO 3.7.1g on Nexus dashboad 2.1.2d

### APIC version and APIC Platform for Site Level Resources

* all

### Collection versions

* all

### References
N/A

**Comment by sajagana** [comment]
Hi @sauguieb 

Description field was added in our latest MSO release. Please refer to the below example to add an EPG with a Description.

```
  - name: Add EPG with description (for version greater than 3.3)
    mso_schema_template_anp_epg:
      host: mso_host
      username: admin
      password: SomeSecretPassword
      schema: ansible_test
      template: Template 1
      anp: ANP
      epg: ansible_test_anp_epg
      description: 'Description of ANP EPG'
      state: present
```
