### ISSUE TITLE
mso_schema_site_anp_epg_staticport

### ISSUE THREAD

**Issue by RonaldBlom** [CiscoDevNet/ansible-mso#282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
[customer_request]

Why the choice was made to have the interfac_mode options differ from APIC and MSO GUI? native and regular versus access and trunk. This means I need to adjust much more than needed in my code and have to ask my customers to give different input and/or changing portals which hook in our automation and provide input. Else I have to translate the input to something we use in the module. I just don't understand why this was needed to gave this different names. For me this is a bug or just a very bad choice. 

* xxxx

### Affected Module Name(s):

mso_schema_site_anp_epg_staticport

* mso_schema_site_anp_epg_staticport

### MSO version and MSO Platform

* V 3.5.2f and ND-based

### APIC version and APIC Platform for Site Level Resources

* V 4.2.6 and on-prem

### Collection versions

* cisco.mso 1.4.0

### Output/ Error message

"msg": "value of mode must be one of: native, regular, untagged, got: trunk"

*

### Expected Behavior

it should just accept the name trunk and access instead of regular and native. Trunk and access is what it is so why change that? 
*

### Actual Behavior

it failed
*

### Playbook tasks to Reproduce

n/a

*

### Important Factoids

no

### References

* #0000

**Comment by akinross** [comment]
Hi Ronald,

This is due to choices made in the past that are inherited throughout the codebase unfortunately. The data-model and the REST API for both MSO & APIC are still using the mode with inputs native, regular, untagged. In the beginning of this repository the choice was made to keep this consistent with the REST API, overtime the GUI was changed several times thus causing inconsistencies between GUI and this repository. 

A change of this will impact our codebase in various locations, and we are trying to keep the codebase as consistent as possible throughout. Also this will impact users that have now implemented the native, regular, untagged modes. So it is a bigger change than it might look upon at first hand. 

I understand your concern and agree with your comments that in hindsight this was a bad choice. Unfortunately we do not know all the changes in advance that will occur. At the moment this is not a change I can do, so for now I would say variable mapping is probably the easiest solution if you want expose your customers to trunk/access or other input values. 

```
---
- name: TESTING
  hosts: all

  tasks:

  - name: Set vars
    set_fact:
      static_mapping: &static_mapping
        trunk: regular
        access: native
      foo: access

  - name: show native
    ansible.builtin.debug:
      msg: "MAPPED VALUE ACCESS; {{ static_mapping[foo] }}"

  - name: show regular
    ansible.builtin.debug:
      msg: "MAPPED VALUE TRUNK; {{ static_mapping['trunk'] }}"
```

Hope this clarifies your issue and apologies for any inconvenience. I will continue with closing the issue, if any follow-up question feel free to reach out.
