### ISSUE TITLE
Add option login domain to httpapi plugin

### ISSUE THREAD

**Issue by WGRBC** [CiscoDevNet/ansible-mso#312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
* Currently the httpapi does not support the login domain global setting. You have to provide the login domain for each module.
* Recommend to add the following code to plugins/httpapi/mso.py in the DOCUMENTATION section
```
    options:
       login_domain:
         type: str
         description:
           - Specifies the MSO login domain
         vars:
           - name: mso_login_domain
```  

### New or Affected Module(s):

* plugins/httpapi/mso.py

### MSO version and MSO Platform

* V x.x.x and Docker Swarm OVA-based/SE-based/ND-based/all.

### APIC version and APIC Platform for Site Level Resources

* V x.x.x and on-prem/cloud-aws/cloud-azure/all.

### Collection versions

* cisco.mso x.x.x

### References

* #0000
