### ISSUE TITLE
cisco.mso collection is not compatible with ansible.netcommon v5.0.0

### ISSUE THREAD

**Issue by andbyrne** [CiscoDevNet/ansible-mso#340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* ansible.netcommon v5.0.0 was recently released and causes issues using the cisco.mso collection

### Affected Module Name(s):

* mso_site (and potentially others)

### MSO version and MSO Platform

* V 3.7.2e and ND V 2.2.2d

### Collection versions

* cisco.mso 2.2.1

### Output/ Error message

```
fatal: [xxxx]: FAILED! => {"changed": false, "current": {}, "data": null, "info": {"body": {"error": "Please refer to /api/config/ndaddsite", "error_code": "gone"}, "connection": "close", "content-length": "69", "content-type": "text/plain; charset=utf-8", "error": {"code": 200, "message": {"error": "Please refer to /api/config/ndaddsite", "error_code": "gone"}}, "method": "GET", "msg": "OK (69 bytes)", "server": "nginx", "status": 410, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://xxxxxx:443/mso/api/v2/sites", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-ratelimit-limit": "-1", "x-ratelimit-remaining": "-1", "x-ratelimit-reset": "1559582945", "x-xss-protection": "1; mode=block"}, "msg": "MSO Error:", "payload": {"error": "Please refer to /api/config/ndaddsite", "error_code": "gone"}, "status": 410}
```

### Playbook tasks to Reproduce

```
    - name: Query sites
      cisco.mso.mso_site:
        state: query
      register: site_data
```

### Important Factoids

Works fine when locking ansible.netcommon to v4.1.0 using the following requirements.yml when installing the collections:

```
---
collections:
  - name: cisco.mso
    version: '>=2.2.1'
  - name: cisco.nd
    version: '>=0.2.0'
  - name: ansible.netcommon
    version: '4.1.0'
...
```
