### ISSUE TITLE
NDO - mso_schema_site_anp_epg_staticport - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by apellini** [CiscoDevNet/ansible-mso#384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using a task with mso_schema_site_anp_epg_staticport module we'll receive NoneType error after migration from MSO to NDO.

### Affected Module Name(s):

* mso_schema_site_anp_epg_staticport

### MSO version and MSO Platform

* V 3.7(2h) and ND-based.

### APIC version and APIC Platform for Site Level Resources

* V 5.2(7g) and on-prem

### Collection versions

* cisco.mso 2.5.0
* cisco.nd 0.4.0

### Output/ Error message

* 'NoneType' object is not iterable

### Expected Behavior

* Configure static port on EPG

### Actual Behavior

* Traceback 'NoneType' object is not iterable

### Playbook tasks to Reproduce

```
- name: Add static port to a site EPG from csv
        cisco.mso.mso_schema_site_anp_epg_staticport:
          host: "{{ inventory_hostname }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          login_domain: "{{ domain }}"
          schema: "{{ item.schema }}"
          site: "{{ item.site }}"
          template: "{{ item.template }}"
          anp: "{{ item.anp }}"
          epg: "{{ item.epg }}"
          type: "{{ item.type }}"
          pod: "{{ item.pod }}"
          leaf: "{{ item.leaf }}"
          path: "{{ item.path | lower }}"
          vlan: "{{ item.vlan | int }}"
          mode: "{{ item.mode }}"
          deployment_immediacy: immediate
          state: present
          validate_certs: false
          use_proxy: no
        delegate_to: localhost
        retries: 3
        until: static_port is not failed
        register: static_port
        check_mode: "{{ mock }}"
        loop: "{{ csvread.list }}"
        when: csvfile is defined and item.type == "port"
```

**Comment by akinross** [comment]
Hi @apellini, Thank you for raising the issue. I will add this to the todo items. Could you provide full logs/traceback?

**Comment by apellini** [comment]
We have done some changes and we see following error:

Authentication failed: HTTP Error 500: Internal Server Error

**Comment by akinross** [comment]
Hi @apellini,

I am not sure what you mean with we made some changes and now we see the following. Without configuration and the tracebacks/logs it would be hard to understand what it is triggering the issue.

**Comment by apellini** [comment]
Below logs in vvv format:

```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: B0J0456
<localhost> EXEC /bin/sh -c 'echo ~B0J0456 && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/B0J0456/.ansible/tmp `"&& mkdir "` echo /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277 `" && echo ansible-tmp-1698737292.7502174-88279-124552911976277="` echo /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277 `" ) && sleep 0'
Using module file /root/.ansible/collections/ansible_collections/cisco/mso/plugins/modules/mso_schema_site_anp_epg_staticport.py
<localhost> PUT /root/.ansible/tmp/ansible-local-88247461opjiw/tmpp034dn6d TO /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277/AnsiballZ_mso_schema_site_anp_epg_staticport.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277/ /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277/AnsiballZ_mso_schema_site_anp_epg_staticport.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/bin/python3.9 /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277/AnsiballZ_mso_schema_site_anp_epg_staticport.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/B0J0456/.ansible/tmp/ansible-tmp-1698737292.7502174-88279-124552911976277/ > /dev/null 2>&1 && sleep 0'
FAILED - RETRYING: [macpnd-cl-api.gtm.corp.sanpaoloimi.com -> localhost]: Add static port to a site EPG from csv (3 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "current": {},
    "invocation": {
        "module_args": {
            "anp": "ANP",
            "deployment_immediacy": "immediate",
            "epg": "EPG",
            "fex": null,
            "host": "macpnd-cl-api.gtm.corp.sanpaoloimi.com",
            "leaf": "1129",
            "login_domain": null,
            "mode": "regular",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "path": "eth1/12",
            "pod": "pod-1",
            "port": null,
            "primary_micro_segment_vlan": null,
            "protocol": "https",
            "schema": "SCHEMA",
            "site": "SITE",
            "state": "present",
            "template": "TEMPLATE",
            "timeout": 30,
            "type": "port",
            "use_proxy": false,
            "use_ssl": true,
            "username": "USERNAME",
            "validate_certs": false,
            "vlan": 2022
        }
    },
    "msg": "Authentication failed: HTTP Error 500: Internal Server Error",
    "retries": 4
}
```

Inventory configuration:
```
all:
  hosts:
    ndo.local:
      ansible_connection: ansible.netcommon.httpapi
      ansible_network_os: cisco.nd.nd
      ansible_httpapi_use_ssl: true
      ansible_httpapi_validate_certs: false
      ansible_httpapi_use_proxy: false
      ansible_httpapi_login_domain: domain
      ansible_ssh_pass: "{{ ansible_password }}"
```
