### ISSUE TITLE
mso_tenant - get error 404 even if tenant exists

### ISSUE THREAD

**Issue by apellini** [CiscoDevNet/ansible-mso#386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Using mso_tenant module we receive 404 error even if tenant exists

### Affected Module Name(s):

* mso_tenant

### MSO version and MSO Platform

* V 3.7(2h) and ND-based.

### APIC version and APIC Platform for Site Level Resources

* V 5.2(7g) and on-prem.

### Collection versions

* cisco.mso 2.5.0
* cisco.nd 0.4.0

### Output/ Error message

```
fatal: [XXXXXXXXX -> localhost]: FAILED! => changed=false 
  attempts: 2
  current: {}
  data: null
  info:
    body: |-
      <html>
      <head><title>404 Not Found</title></head>
      <body>
      <center><h1>404 Not Found</h1></center>
      <hr><center>nginx</center>
      </body>
      </html>
    connection: close
    content-length: '146'
    content-type: text/html
    date: Sun, 05 Nov 2023 09:00:16 GMT
    msg: 'HTTP Error 404: Not Found'
    referrer-policy: strict-origin-when-cross-origin
    status: 404
    strict-transport-security: max-age=31536000; includeSubDomains
    url: https://XXXXXXXXX/api/v1/users
    x-content-type-options: nosniff
    x-frame-options: SAMEORIGIN
    x-ratelimit-limit: '0'
    x-ratelimit-remaining: '0'
    x-ratelimit-reset: '0'
    x-xss-protection: 1; mode=block
  msg: 'MSO Error:'
  raw: |-
    <html>
    <head><title>404 Not Found</title></head>
    <body>
    <center><h1>404 Not Found</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>
  status: 404
```

### Expected Behavior

* We expect task in OK state because Tenant Exists.

### Actual Behavior

* 404 Error. Other modules used, like mso_schema are working.

### Playbook tasks to Reproduce

```
tasks:
    ##########################################
    # Create DR Tenant and relative template #
    ##########################################
    - name: Create DR tenant
      cisco.mso.mso_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        tenant: TENANT
        description: My Tenant
        validate_certs: false
        use_proxy: false
        timeout: "{{ mso.timeout }}"
        state: present
      delegate_to: localhost
      retries: "{{ mso.retry }}"
      until: json_tenant is not failed
      register: json_tenant
```

### Important Factoids

None

### References

None

**Comment by akinross** [comment]
Hi @apellini,

I'm not sure what it your setup is but when suspect this has to do with you setting `delegate_to: localhost` in the task.

When I run the following:

```
---
- name: TESTING
  hosts: all

  tasks:

    - name: Set vars
      ansible.builtin.set_fact:
        mso_info: &mso_info
          host: '{{ mso_hostname }}'
          username: '{{ mso_username }}'
          password: '{{ mso_password }}'
          validate_certs: '{{ mso_validate_certs | default(false) }}'
          use_ssl: '{{ mso_use_ssl | default(true) }}'
          use_proxy: '{{ mso_use_proxy | default(true) }}'
          output_level: debug

    - name: Query MSO version
      cisco.mso.mso_version:
        <<: *mso_info
        state: query
      register: version

    - name: Add tenant
      cisco.mso.mso_tenant: &tenant_present
        <<: *mso_info
        tenant: abr_test
        display_name: ABR test display name
        description: ABR test tenant
        state: present

    - name: Add tenant again
      cisco.mso.mso_tenant:
        <<: *tenant_present

    - name: Remove tenant
      cisco.mso.mso_tenant:
        <<: *tenant_present
        state: absent
```

I get the following result:

```
root@e257f89efa3e:/test# ansible-playbook -i inventories/inventory.networking.mso main.yaml 
[WARNING]: While constructing a mapping from /test/main.yaml, line 173, column 9, found a duplicate dict key (state).
Using last defined value only.

PLAY [TESTING] ********************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [ndo-v372]

TASK [Set vars] *******************************************************************************************************
ok: [ndo-v372]

TASK [Query MSO version] **********************************************************************************************
ok: [ndo-v372]

TASK [Add tenant] *****************************************************************************************************
changed: [ndo-v372]

TASK [Add tenant again] ***********************************************************************************************
ok: [ndo-v372]

TASK [Remove tenant] **************************************************************************************************
changed: [ndo-v372]

PLAY RECAP ************************************************************************************************************
ndo-v372      : ok=6    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

When I set `delegate_to: localhost` command your error occurs:

```
fatal: [ -> localhost]: FAILED! => {"changed": false, "current": {}, "data": null, "httpapi_logs": [], "info": {"body": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", "connection": "close", "content-length": "146", "content-type": "text/html", "date": "Mon, 06 Nov 2023 07:25:56 GMT", "msg": "HTTP Error 404: Not Found", "server": "nginx", "status": 404, "strict-transport-security": "max-age=31536000; includeSubDomains", "url": "https://<IP-ADDRESS>/api/v1/users", "x-content-type-options": "nosniff", "x-frame-options": "SAMEORIGIN", "x-ratelimit-limit": "0", "x-ratelimit-remaining": "0", "x-ratelimit-reset": "0", "x-xss-protection": "1; mode=block"}, "method": "GET", "msg": "MSO Error:", "previous": {}, "proposed": {}, "raw": "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n", "response": "HTTP Error 404: Not Found", "sent": {}, "socket": null, "status": 404, "url": "https://<IP-ADDRESS>/api/v1/users"}
```
