### ISSUE TITLE
cisco.mso.mso_rest returns unhelpful error response (DCNE-49)

### ISSUE THREAD

**Issue by phil-dotchon** [CiscoDevNet/ansible-mso#423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* When using `cisco.mso.mso_rest` to patch NDO schema I ran into some issues. The code was previously working on earlier NDO (`3.7.(1j)`) and collection version (`2.2.1`), but after upgrade to `4.2.3e`, along with update of the collection from `2.2.1` to `2.6.0` the code no longer worked. This problem is now resolved, but to find the cause I needed to use Postman as the output returned by `mso-rest` was quite unhelpful for some reason. The raw output returned from Postman, for the exact same request, provided a clear insight into what was going wrong in the API call

### Affected Module Name(s):

* mso_rest

### MSO version and MSO Platform

* V  `4.2.3e` and ND-based.

### APIC version and APIC Platform for Site Level Resources

* V `5.3(2b)` and on-prem

### Collection versions

* cisco.mso `2.6.0`

### Output/ Error message

* Output from `mso_rest`
```
{
    "attempts": 1,
    "changed": false,
    "current": {},
    "data": [
        {
            "op": "add",
            "path": "/templates/CommonTemplate_001/contracts/CI9380650/serviceGraphRelationship",
            "value": {
                "serviceGraphContractRelationRef": {
                    "contractName": "CI9380650",
                    "schemaId": "663a169d216a38e187135157",
                    "serviceGraphName": "PA-5250-PBR_non-production",
                    "templateName": "CommonTemplate_001"
                },
                "serviceGraphRef": {
                    "schemaId": "663a169d216a38e187135157",
                    "serviceGraphName": "PA-5250-PBR_non-production",
                    "templateName": "CommonTemplate_001"
                },
                "serviceNodesRelationship": [
                    {
                        "consumerConnector": {
                            "bdRef": {
                                "bdName": "ips-pbr-transit_non-production_e-us1",
                                "schemaId": "663529ef216a38e187132625",
                                "templateName": "Infrastructure_e-us1"
                            },
                            "connectorType": "general"
                        },
                        "providerConnector": {
                            "bdRef": {
                                "bdName": "ips-pbr-transit_non-production_e-us1",
                                "schemaId": "663529ef216a38e187132625",
                                "templateName": "Infrastructure_e-us1"
                            },
                            "connectorType": "general"
                        },
                        "serviceNodeRef": {
                            "schemaId": "663a169d216a38e187135157",
                            "serviceGraphName": "PA-5250-PBR_non-production",
                            "serviceNodeName": "node1",
                            "templateName": "CommonTemplate_001"
                        }
                    }
                ]
            }
        }
    ],
    "httpapi_logs": [
        [
            "info",
            "send_request() - send_request method called"
        ],
        [
            "info",
            "send_request() - connection.send(/mso/api/v1/schemas/663a169d216a38e187135157?validate=false, [{\"op\": \"add\", \"path\": \"/templates/CommonTemplate_001/contracts/CI9380650/serviceGraphRelationship\", \"value\": {\"serviceGraphRef\": {\"templateName\": \"CommonTemplate_001\", \"serviceGraphName\": \"PA-5250-PBR_non-production\", \"schemaId\": \"663a169d216a38e187135157\"}, \"serviceGraphContractRelationRef\": {\"templateName\": \"CommonTemplate_001\", \"serviceGraphName\": \"PA-5250-PBR_non-production\", \"contractName\": \"CI9380650\", \"schemaId\": \"663a169d216a38e187135157\"}, \"serviceNodesRelationship\": [{\"serviceNodeRef\": {\"templateName\": \"CommonTemplate_001\", \"serviceGraphName\": \"PA-5250-PBR_non-production\", \"schemaId\": \"663a169d216a38e187135157\", \"serviceNodeName\": \"node1\"}, \"consumerConnector\": {\"bdRef\": {\"templateName\": \"Infrastructure_e-us1\", \"bdName\": \"ips-pbr-transit_non-production_e-us1\", \"schemaId\": \"663529ef216a38e187132625\"}, \"connectorType\": \"general\"}, \"providerConnector\": {\"bdRef\": {\"templateName\": \"Infrastructure_e-us1\", \"bdName\": \"ips-pbr-transit_non-production_e-us1\", \"schemaId\": \"663529ef216a38e187132625\"}, \"connectorType\": \"general\"}}]}}], PATCH, {'Content-Type': 'application/json'})"
        ],
        [
            "vvv",
            "ESTABLISH HTTP(S) CONNECTFOR USER: xxxxxx TO https://e-us1-ndo.fis.lab:443"
        ],
        [
            "info",
            "login() - login method called for e-us1-ndo.fis.lab"
        ],
        [
            "info",
            "login() - previous auth not found sending login POST to e-us1-ndo.fis.lab"
        ],
        [
            "info",
            "login() - connection.send(/login, LOGIN_PAYLOAD_NOT_SHOWN, POST, {'Content-Type': 'application/json'})"
        ]
    ],
    "info": {
        "body": {
            "error": "There was an internal server error"
        },
        "connection": "close",
        "content-length": "46",
        "content-type": "application/json",
        "error": {
            "code": 200,
            "message": {
                "error": "There was an internal server error"
            }
        },
        "method": "PATCH",
        "msg": "OK (46 bytes)",
        "server": "nginx",
        "status": 500,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": "https://e-us1-ndo.fis.lab:443/mso/api/v1/schemas/663a169d216a38e187135157?validate=false",
        "x-ratelimit-limit": "-1",
        "x-ratelimit-remaining": "-1",
        "x-ratelimit-reset": "1559582945"
    },
    "method": "PATCH",
    "msg": "MSO Error:",
    "payload": {
        "error": "There was an internal server error"
    },
    "response": "OK (46 bytes)",
    "socket": "/home/lc5648734/.ansible/pc/39504a262a",
    "status": 500,
    "url": "https://e-us1-ndo.fis.lab:443/mso/api/v1/schemas/663a169d216a38e187135157?validate=false"
}
```

### Expected Behavior

* Output from Postman
```
{
    "code": 400,
    "message": "site-local Contract CI9380650 in site e-us-site1 in template CommonTemplate_001: missing Service Graph configuration",
    "info": null
}
```

### Actual Behavior

* The output from the `mso_rest` module in Ansible seems to have lost/dropped the useful info returned by the API endpoint, so the helpful text explaining why the API call failed is missing. I would expect the module to give me the useful info so I could correct the code and not have to resort to constructing the faulty call in Postman in order to understand what is going wrong

### Playbook tasks to Reproduce

```
    - name: Add service graph to template contract
      ignore_errors: true
      cisco.mso.mso_rest:
        host: "{{ ansible_host | mandatory }}"
        username: "{{ ansible_user | mandatory }}"
        password: "{{ ansible_password | mandatory }}"
        validate_certs: "{{ ansible_httpapi_validate_certs }}"
        use_ssl: "{{ ansible_httpapi_use_ssl }}"
        use_proxy: false
        timeout: "{{ mso_timeout | default(omit) }}"
        path: "/mso/api/v1/schemas/663a169d216a38e187135157"
        method: patch
        output_level: debug
        content:
          - op: add
            path: "/templates/CommonTemplate_001/contracts/CI9380650/serviceGraphRelationship"
            value:
              serviceGraphRef:
                templateName: CommonTemplate_001
                serviceGraphName: PA-5250-PBR_non-production
                schemaId: 663a169d216a38e187135157
              serviceGraphContractRelationRef:
                templateName: CommonTemplate_001
                serviceGraphName: PA-5250-PBR_non-production
                contractName: CI9380650
                schemaId: 663a169d216a38e187135157
              serviceNodesRelationship:
                - serviceNodeRef:
                    templateName: CommonTemplate_001
                    serviceGraphName: PA-5250-PBR_non-production
                    schemaId: 663a169d216a38e187135157
                    serviceNodeName: node1
                  consumerConnector:
                    bdRef:
                      templateName: Infrastructure_e-us1
                      bdName: ips-pbr-transit_non-production_e-us1
                      schemaId: 663529ef216a38e187132625
                    connectorType: general
                  providerConnector:
                    bdRef:
                      templateName: Infrastructure_e-us1
                      bdName: ips-pbr-transit_non-production_e-us1
                      schemaId: 663529ef216a38e187132625
                    connectorType: general
```
Postman call:
```
https://x.x.x.x/mso/api/v1/schemas/663a169d216a38e187135157

[
    {
        "op": "add",
        "path": "/templates/CommonTemplate_001/contracts/CI9380650/serviceGraphRelationship",
        "value": {
            "serviceGraphRef": {
                "templateName": "CommonTemplate_001",
                "serviceGraphName": "PA-5250-PBR_non-production",
                "schemaId": "663a169d216a38e187135157"
            },
            "serviceGraphContractRelationRef": {
                "templateName": "CommonTemplate_001",
                "serviceGraphName": "PA-5250-PBR_non-production",
                "contractName": "CI9380650",
                "schemaId": "663a169d216a38e187135157"
            },
            "serviceNodesRelationship": [
                {
                    "serviceNodeRef": {
                        "templateName": "CommonTemplate_001",
                        "serviceGraphName": "PA-5250-PBR_non-production",
                        "schemaId": "663a169d216a38e187135157",
                        "serviceNodeName": "node1"
                    },
                    "consumerConnector": {
                        "bdRef": {
                            "templateName": "Infrastructure_e-us1",
                            "bdName": "ips-pbr-transit_non-production_e-us1",
                            "schemaId": "663529ef216a38e187132625"
                        },
                        "connectorType": "general"
                    },
                    "providerConnector": {
                        "bdRef": {
                            "templateName": "Infrastructure_e-us1",
                            "bdName": "ips-pbr-transit_non-production_e-us1",
                            "schemaId": "663529ef216a38e187132625"
                        },
                        "connectorType": "general"
                    }
                }
            ]
        }
    }
]
```

### Important Factoids

The reason for the failure is that NDO now requires the template and site level contract service graph structures to be provided at the same time, in the same API call, whereas in previous versions this could be delivered as two separate calls.

### References

* #0000
