### ISSUE TITLE
Adding Mulicast Route-map policy configuration on existing RP (Rendezvous Point) fails when previous RM is empty (DCNE-304)

### ISSUE THREAD

**Issue by hsbachiri** [CiscoDevNet/ansible-mso#612]
### Description

•	Cannot add a Multicast Route-map policy on existing RP when previous value is empty.
•	Failure is not seen when a RM is already associated to the RP.

For instance, these two scenarios are working:
•	push playbook with the same RM as the current one configured under the RP.
•	replace an existing Multicast RM-Policy under the RP.

### Affected Module Name(s):

•	mso_schema_template_vrf_rp

### MSO version and MSO Platform

ND: 3.0.1i
NDO: 4.2(3k) / 4.4.1.1012

### APIC version and APIC Platform for Site Level Resources

APIC: 5.3(2c)

### Collection versions

•	cisco.mso 2.9.0

### Output/ Error message
```
FAILED! => {
    "changed": true,
    "current": {
        "ipAddress": "1.1.1.1",
        "mcastRtMapPolicyRef": "3a67e754-cfbc-4932-89a8-4be2ecc68299",
        "rpType": "static",
        "version": 0
    },
    "data": [
        {
            "op": "replace",
            "path": "/templates/VRF_TMP/vrfs/VRF01-HSM/rpConfigs/0/mcastRtMapPolicyRef",
            "value": "3a67e754-cfbc-4932-89a8-4be2ecc68299"
        }
    ],
    "info": {
        "body": {
            "code": 400,
            "message": "replace operation does not apply: doc is missing key: /templates/0/vrfs/0/rpConfigs/0/mcastRtMapPolicyRef: missing value"
        },
        "connection": "close",
        "content-language": "en",
        "content-length": "145",
        "content-type": "application/json",
        "error": {
            "code": -1,
            "message": {
                "code": 400,
                "message": "replace operation does not apply: doc is missing key: /templates/0/vrfs/0/rpConfigs/0/mcastRtMapPolicyRef: missing value"
            }
        },
        "method": "PATCH",
        "msg": "OK (145 bytes)",
        "server": "nginx",
        "status": 400,
        "strict-transport-security": "max-age=31536000; includeSubDomains",
        "url": [https://***********:443/mso/api/v1/schemas/679a3c3fb0a1b7cdc668e489?validate=false](https://***********/mso/api/v1/schemas/679a3c3fb0a1b7cdc668e489?validate=false),
        "x-ratelimit-limit": "-1",
        "x-ratelimit-remaining": "-1",
        "x-ratelimit-reset": "1559582945"
    },
    "invocation": {
        "module_args": {
            "host": "**************",
            "ip": "1.1.1.1",
            "login_domain": null,
            "multicast_route_map_policy": "MCAST_RM_FILTER_MAN_RP",
            "output_level": "normal",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "schema": "User8-schema-HSM",
            "state": "present",
            "template": "VRF_TMP",
            "timeout": null,
            "type": "static",
            "use_proxy": null,
            "use_ssl": null,
            "username": "user8-global",
            "validate_certs": false,
            "vrf": "VRF01-HSM"
        }
    },
    "msg": "MSO Error 400: replace operation does not apply: doc is missing key: /templates/0/vrfs/0/rpConfigs/0/mcastRtMapPolicyRef: missing value",
    "payload": {
        "code": 400,
        "message": "replace operation does not apply: doc is missing key: /templates/0/vrfs/0/rpConfigs/0/mcastRtMapPolicyRef: missing value"
    },
    "status": 400
}
```
### Expected Behavior

•	Associate/add new Multicast Route-map Policy on existing RP

### Actual Behavior

•	error at playbook execution

### Playbook tasks to Reproduce
```
---
- name: ===== NDO 4.2(3k) / ND 3.0(1i) Testing =====
  hosts: ndo
  connection: local
  gather_facts: false

  tasks:
    - name: ===== Add Multicast RM Policy on existing Static RP =====
      cisco.mso.mso_schema_template_vrf_rp:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        schema: User8-schema-HSM
        template: VRF_TMP
        vrf: VRF01-HSM
        ip: 1.1.1.1
        type: static
        multicast_route_map_policy: MCAST_RM_FILTER_MAN_RP
        state: present

    - name: ===== Add Multicast RM Policy on existing Fabric RP =====
      cisco.mso.mso_schema_template_vrf_rp:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        schema: User8-schema-HSM
        template: VRF_TMP
        vrf: VRF01-HSM
        ip: 10.99.99.99
        type: fabric
        multicast_route_map_policy: MCAST_RM_FILTER_FABRIC_RP
        state: present
```
